version: '3.7'

networks:
  network-banco:
    name: lbd-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/29

volumes:
  postgres-withdb-data:
  pgadmin-withdb-data:

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: psqldata
    container_name: lbd-pgadmin
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-withdb-data:/var/lib/postgresql/data
    networks:
      network-banco:
        ipv4_address: 172.20.0.2
    restart: unless-stopped


  pgAdmin4:
    container_name: pgAdmin4_interface
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    depends_on: 
      - postgres
    ports:
      - 80
    volumes:
      - pgadmin-withdb-data:/var/lib/pgadmin
      - pgadmin-withdb-data:/certs/server.cert
      - pgadmin-withdb-data:/certs/server.key
      - pgadmin-withdb-data:/pgadmin4/servers.json
    networks:
      network-banco:
        ipv4_address: 172.20.0.3
    restart: unless-stopped
        